"""message

Revision ID: 1aea4b3686f6
Revises: 1e95e74b428e
Create Date: 2020-05-16 21:43:03.349176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aea4b3686f6'
down_revision = '1e95e74b428e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='评论用户的 ID'),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='Post 文章的 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='用户的评论'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='改项目是否被删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comment')
    op.alter_column('post', 'content',
               existing_type=mysql.TEXT(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.create_table('comment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='评论用户的 ID'),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Post 文章的 ID'),
    sa.Column('content', mysql.TEXT(), nullable=False, comment='用户的评论'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='改项目是否被删除'),
    sa.CheckConstraint('(`deleted` in (0,1))', name='comment_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('comments')
    # ### end Alembic commands ###
