"""message

Revision ID: 2583a49a57d4
Revises: 1aea4b3686f6
Create Date: 2020-05-16 21:45:18.936437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2583a49a57d4'
down_revision = '1aea4b3686f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    op.drop_table('post')
    op.drop_table('user')
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='评论用户的 ID'),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Post 文章的 ID'),
    sa.Column('content', mysql.TEXT(), nullable=False, comment='用户的评论'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='改项目是否被删除'),
    sa.CheckConstraint('(`deleted` in (0,1))', name='comments_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False, comment='登陆密码 hash 之后的值'),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True, comment='电话号码'),
    sa.Column('avatar', mysql.VARCHAR(length=256), nullable=True, comment='用户头像'),
    sa.Column('website', mysql.VARCHAR(length=100), nullable=True, comment='个人网站'),
    sa.Column('company', mysql.VARCHAR(length=100), nullable=True, comment='所在公司'),
    sa.Column('job', mysql.VARCHAR(length=100), nullable=True, comment='职位'),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True, comment='所在地'),
    sa.Column('signature', mysql.VARCHAR(length=256), nullable=True, comment='签名'),
    sa.Column('Dribbble', mysql.VARCHAR(length=256), nullable=True, comment='Dribbble'),
    sa.Column('Duolingo', mysql.VARCHAR(length=256), nullable=True, comment='Duolingo'),
    sa.Column('About_me', mysql.VARCHAR(length=256), nullable=True, comment='About.me'),
    sa.Column('Last_me', mysql.VARCHAR(length=256), nullable=True, comment='Last.fm'),
    sa.Column('Goodreads', mysql.VARCHAR(length=256), nullable=True, comment='Goodreads'),
    sa.Column('GitHub', mysql.VARCHAR(length=256), nullable=True, comment='GitHub'),
    sa.Column('PSN_ID', mysql.VARCHAR(length=256), nullable=True, comment='PSN ID'),
    sa.Column('Steam_ID', mysql.VARCHAR(length=256), nullable=True, comment='Steam_ID'),
    sa.Column('Twitch', mysql.VARCHAR(length=256), nullable=True, comment='Twitch'),
    sa.Column('BattleTag', mysql.VARCHAR(length=256), nullable=True, comment='BattleTag'),
    sa.Column('Instagram', mysql.VARCHAR(length=256), nullable=True, comment='Instagram'),
    sa.Column('Telegram', mysql.VARCHAR(length=256), nullable=True, comment='Telegram'),
    sa.Column('Twitter', mysql.VARCHAR(length=256), nullable=True, comment='Twitter'),
    sa.Column('BTC_Address', mysql.VARCHAR(length=256), nullable=True, comment='BTC Address'),
    sa.Column('Coding_net', mysql.VARCHAR(length=256), nullable=True, comment='Coding.net'),
    sa.Column('Personal_Introduction', mysql.VARCHAR(length=256), nullable=True, comment='个人简介'),
    sa.Column('state_update_view_permission', mysql.INTEGER(), autoincrement=False, nullable=True, comment='状态更新查看权限'),
    sa.Column('community_rich_rank', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='社区财富排行榜'),
    sa.Column('money', mysql.INTEGER(), autoincrement=False, nullable=True, comment='余额'),
    sa.Column('show_remain_money', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否显示余额'),
    sa.Column('use_avatar_for_favicon', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='使用节点头像作为页面 favicon'),
    sa.Column('use_high_resolution_avatar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='使用高精度头像'),
    sa.Column('time_zone', mysql.VARCHAR(length=256), nullable=True, comment='默认使用的时区'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='改项目是否被删除'),
    sa.CheckConstraint('(`community_rich_rank` in (0,1))', name='user_chk_1'),
    sa.CheckConstraint('(`deleted` in (0,1))', name='user_chk_5'),
    sa.CheckConstraint('(`show_remain_money` in (0,1))', name='user_chk_2'),
    sa.CheckConstraint('(`use_avatar_for_favicon` in (0,1))', name='user_chk_3'),
    sa.CheckConstraint('(`use_high_resolution_avatar` in (0,1))', name='user_chk_4'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='文章所在的主题 ID'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='发布文章用户的 ID'),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('click_times', mysql.INTEGER(), autoincrement=False, nullable=True, comment='文章的点击数'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='文章的 tag'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='改项目是否被删除'),
    sa.CheckConstraint('(`deleted` in (0,1))', name='post_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('topic',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='该项目是否被删除'),
    sa.CheckConstraint('(`deleted` in (0,1))', name='topic_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
